<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ApplicationIcon>app.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="app.ico"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(SourceDir)RandomStringGeneration\RandomStringGeneration.csproj"/>
        <ProjectReference Include="$(SourceDir)ShortcutScriptGeneration\ShortcutScriptGeneration.csproj"/>
        <ProjectReference Include="$(SourceDir)Logging\Logging.csproj"/>
    </ItemGroup>
</Project>
