
version: "3.9"
services:
  mkdocs:
    image: sparklitwizzl/petrichor-documentation:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: serve -a "0.0.0.0:8000"
    ports:
      - "8005:8000"
    volumes:
      - .:/usr/src/mkdocs/build
