site_name: Petrichor 0.11.0
site_author: SparkliTwizzl
copyright: Copyright (c) 2024 SparkliTwizzl. Licensed under AEL-NC-AT 1.1.
repo_url: https://github.com/sparklitwizzl/petrichor
use_directory_urls: false
nav:
    - 'Getting started':
        - user-guide/getting-started/overview.md
        - user-guide/getting-started/petrichor-script.md
        - user-guide/getting-started/command-usage.md
    - 'Text Shortcut Script Generation module':
        - user-guide/text-shortcut-script-generation-module/overview.md
        - user-guide/text-shortcut-script-generation-module/petrichor-script.md
        - user-guide/text-shortcut-script-generation-module/command.md
        - user-guide/text-shortcut-script-generation-module/running-output-scripts.md
    - About:
        - about/release-notes.md
        - about/license.md
